### ISSUE TITLE
Reduce observing interval

### ISSUE THREAD

**Issue by YiRanMushroom** [gigabite-pro/byeClicker#1]
I used this plugin in chrome, and it doesn't seems to work very well, The auto join feature is fine, but the auto click feature seems not working from time to time. Most of the time it could not respond(at least it didn't respond in several seconds after the website refreshed). I suspect that the time interval of detecting the site is too long. I don't quite know javascript and I cannot test the plugin so I can't further investigate and fix it. Could you try to reduce the time so that it can work?

**Comment by gigabite-pro** [comment]
Hi! Thank you for the feedback. The time delay between the page load and the auto click is about 10 seconds. However, I am not listening for page load but content load since the page is loading only once and the content is changing on it as a new question loads. The content takes about 4 seconds to load properly plus 10 seconds delay makes it about 14 seconds total. After 14 seconds, you should see your answer being selected. iClicker has this thing of loading the page randomly if the content doesn't load properly, and that stops my extension ByeClicker and resets it. You may be facing this issue due to a bad network since it is working fine for everyone using Chrome.

**Comment by YiRanMushroom** [comment]
Maybe it's just our instructor give us too little time so it can not work for some of them.

**Comment by gigabite-pro** [comment]
Hi! There was an issue with the API. I have corrected the error. It should work for you now. Thanks for reporting.

**Comment by YiRanMushroom** [comment]
Okay thanks now I can skip the apsc 160 morning classes for a good nap. C is just too easy and I don't want to listen to the boring lectures.

**Comment by YiRanMushroom** [comment]
Also do I need to update that or it will be automatically updated?

**Comment by gigabite-pro** [comment]
It'll update automatically.
